# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZSZwfsKxXQ0RhwqSrfpkzOzeHsbcY5c0
"""

!pip install -q streamlit
# sueldo_usm_app.py
import streamlit as st
import requests
import pandas as pd
import plotly.express as px

# --- CONFIGURACIÓN DE PÁGINA ---
st.set_page_config(
    page_title="Calculadora Salarial USM",
    page_icon="📊",
    layout="centered"
)

# --- FUNCIÓN PARA OBTENER UF Y UTM ACTUALIZADAS ---
@st.cache_data(ttl=3600)
def get_indicadores():
    try:
        response = requests.get("https://mindicador.cl/api")
        data = response.json()
        return data['uf']['valor'], data['utm']['valor']
    except:
        # Valores de respaldo en caso de error de conexión
        return 38100.0, 66600.0

uf_actual, utm_actual = get_indicadores()

# --- TÍTULO E INTERFAZ ---
st.title("📊 Calculadora Salarial Personalizada")
st.markdown(f"**Indicadores del día:** UF: `${uf_actual:,.2f}` | UTM: `${utm_actual:,.0f}`")
st.divider()

# --- INPUTS (VALORES POR DEFECTO SEGÚN TUS LIQUIDACIONES) ---
col1, col2 = st.columns(2)

with col1:
    st.subheader("💰 Ingresos")
    sueldo_base = st.number_input("Sueldo Base", value=2409363)
    asig_fijas = st.number_input("Asignaciones (Antigüedad, Título, etc.)", value=228033)
    bono_usm = st.number_input("Bonificación USM (Bruta)", value=0)
    asig_teletrabajo = st.number_input("Asignación Teletrabajo (No imponible)", value=3810)

with col2:
    st.subheader("📉 Descuentos y Ahorro")
    plan_isapre_uf = st.number_input("Plan Isapre Pactado (UF)", value=6.32, step=0.01)
    apv_monto = st.number_input("APV Mensual (Régimen B)", value=0)
    seguro_salud = st.number_input("Seguro Complementario Salud ($)", value=0)

# --- LÓGICA DE CÁLCULO ---
total_imponible = sueldo_base + asig_fijas + bono_usm
tope_imponible_afp = 84.3 * uf_actual # Tope imponible aproximado

# 1. Leyes Sociales
base_calculo = min(total_imponible, tope_imponible_afp)
monto_afp = base_calculo * 0.1127 # Tasa Habitat según tu archivo
monto_cesantia = total_imponible * 0.006 # 0.6% cargo trabajador (Indefinido)

# Salud Isapre: Se paga el mayor entre el 7% legal o el plan pactado
siete_por_ciento = base_calculo * 0.07
costo_isapre_pesos = plan_isapre_uf * uf_actual
monto_salud_final = max(siete_por_ciento, costo_isapre_pesos)

# 2. Impuesto Único (Cálculo por tramos según UTM)
# Base tributable = Imponible - Cotizaciones Legales (sin incluir el adicional de Isapre) - APV
base_tributable = total_imponible - monto_afp - siete_por_ciento - monto_cesantia - apv_monto
base_en_utm = base_tributable / utm_actual

if base_en_utm <= 13.5:
    impuesto = 0
elif base_en_utm <= 30:
    impuesto = (base_tributable * 0.04) - (0.54 * utm_actual)
elif base_en_utm <= 50:
    impuesto = (base_tributable * 0.08) - (1.74 * utm_actual)
else:
    impuesto = (base_tributable * 0.135) - (4.49 * utm_actual)

impuesto = max(0, impuesto)

# 3. El factor "Anticipo" (Solo si hay bono)
anticipo_descuento = bono_usm * 0.8583 if bono_usm > 0 else 0

# 4. Resultado Líquido
descuentos_totales = monto_afp + monto_salud_final + monto_cesantia + impuesto + apv_monto + seguro_salud + anticipo_descuento
total_haberes = total_imponible + asig_teletrabajo
sueldo_liquido = total_haberes - descuentos_totales

# --- DESPLIEGUE DE RESULTADOS ---
st.divider()
c1, c2 = st.columns(2)
c1.metric("LÍQUIDO A RECIBIR", f"${sueldo_liquido:,.0f}")
c2.metric("COSTO TOTAL IMPUESTOS", f"${impuesto:,.0f}")

# --- GRÁFICO ---
labels = ["Sueldo Líquido", "AFP", "Salud (Isapre)", "Impuesto Único", "Otros/Anticipo"]
valores = [sueldo_liquido, monto_afp, monto_salud_final, impuesto, (apv_monto + seguro_salud + anticipo_descuento)]

df_chart = pd.DataFrame({"Concepto": labels, "Monto": valores})
fig = px.pie(df_chart, values='Monto', names='Concepto', hole=0.4, title="Distribución de tu Sueldo Bruto")
st.plotly_chart(fig)

# --- CÁLCULO POR HORA Y ANUAL ---
st.subheader("⏱️ Análisis de Valor Tiempo")
# 44 horas semanales = ~190.6 horas mensuales
horas_mensuales = 190.6
v_hora_bruto = total_imponible / horas_mensuales
v_hora_liquido = sueldo_liquido / horas_mensuales

st.write(f"Tu valor hora bruto es de: **${v_hora_bruto:,.0f}**")
st.write(f"Tu valor hora líquido es de: **${v_hora_liquido:,.0f}**")

st.subheader("📅 Proyección Anual")
st.write(f"Sueldo Líquido Anual Estimado: **${(sueldo_liquido * 12):,.0f}**")